# Generated by Django 5.0.2 on 2024-02-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recado',
            name='texto',
            field=models.TextField(default=''),
        ),
    ]
